server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password: 1
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: kafka-log-service
  kafka:
    bootstrap-servers: 127.0.0.1:9092 #服务器的ip及端口，可以写多个，服务器之间用“：”间隔
    consumer: #消费者配置
      group-id: inventory-log-group #设置消费者的组id
      enable-auto-commit: true
      # auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  sleuth:
    sampler:
      probability: 1.0 # 采样率，1.0 表示所有请求都采样
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.wang: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: BASIC
#  httpclient:
#    enabled: true
#    max-connections: 200
#    max-connections-per-route: 50
#    time-to-live: 900