server:
  port: 9080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service # 路由id，自定义，只要唯一即可
          uri: lb://user-service # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就会路由到user-service
        - id: order-service
          uri: lb://order-service
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/order/** # 这个是按照路径匹配，只要以/order/开头就会路由到order-service
        - id: inventory-order-service
          uri: lb://inventory-order-service
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/inventory/** # 这个是按照路径匹配，只要以/order/开头就会路由到order-service



#        - id: kafka-log-service
#          uri: lb://kafka-log-service
#          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/

